# Generated by Django 4.1.5 on 2023-01-28 06:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=150)),
                ('Sobrenome', models.CharField(blank=True, max_length=150)),
                ('Telefone', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^[1-9]{2}\\d{9}$')])),
                ('Email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('Data_de_criação', models.DateTimeField(default=django.utils.timezone.now)),
                ('Descrição', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, upload_to='img/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'webp', 'jpeg'])])),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='homepage.categoria')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
