# Generated by Django 4.1.5 on 2023-01-31 20:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_alter_contato_email_alter_contato_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='Telefone',
            field=models.CharField(error_messages=['Informe um telefone válido.'], max_length=11, validators=[django.core.validators.RegexValidator('^[1-9]{2}\\d{9}$')]),
        ),
    ]
